### ISSUE TITLE
Pair1: Implement and measure performance of chosen workloads in java

### ISSUE THREAD

**Issue by rehnarama** [Melkster/voc#21]
For workload chosen in #19  "Implement the chosen workloads in Java and measure their performance on the Java implementation of the Python datatype. Use profiling to figure out what the hotspots are."

# Tasks
- [x] Workload 1: Concatenate many big lists
- [x] Workload 2: Sort a large list
- [x] Workload 3: Many random reads in a big list
- [x] Measure the performance of the workloads
- [x] Profile to find hotspots

**Comment by jowe3751** [comment]
# Performance

## Concatenate many big lists

**Runtime:** 0.050s

![Concatenate many big lists](http://user.it.uu.se/~meos6185/maintenance_sprint3/ConcatenateList_old.png)

## Sort a large list

**Runtime:** 0.959s

![Sort a large list](http://user.it.uu.se/~meos6185/maintenance_sprint3/SortLargeList_old.png)

## Read randomly from list

**Runtime:** 0.058s

![Read randomly from list](http://user.it.uu.se/~meos6185/maintenance_sprint3/RandomReadsList_old.png)
