### ISSUE TITLE
Pair2: Implement and measure performance of chosen workloads in java

### ISSUE THREAD

**Issue by rehnarama** [Melkster/voc#22]
For workload chosen in #19  "Implement the chosen workloads in Java and measure their performance on the Java implementation of the Python datatype. Use profiling to figure out what the hotspots are."

# Tasks
- [x] Workload 4 (Sum all integers in a big list)
- [x] Workload 5 (Insert many items into the begining of a list)
- [x] Workload 6 (Remove elements from a list at random indexes)
- [x] Measure the performance of the workloads
- [x] Profile to find hotspots

**Comment by AdamInersjo** [comment]
# Performance

## SumNumbers
* **Runtime**: 0.009499 s
* **Memory usage**: 12.29 MB

![](http://user.it.uu.se/~jono4597/mp_course/sprint3/sum_numbers_class_profile.png)
![](http://user.it.uu.se/~jono4597/mp_course/sprint3/sum_numbers_method_profile.png)

## InsertMany
* **Runtime**: 0.795548 s
* **Memory usage**: 56.11 MB

![](http://user.it.uu.se/~jono4597/mp_course/sprint3/insert_many_class_profile.png)
![](http://user.it.uu.se/~jono4597/mp_course/sprint3/insert_many_method_profile.png)

## RandomRemoves
* **Runtime**: 1.028677 s
* **Memory usage**: 212.9 MB

![](http://user.it.uu.se/~jono4597/mp_course/sprint3/random_removes_class_profile.png)
![](http://user.it.uu.se/~jono4597/mp_course/sprint3/random_removes_method_profile.png)
